- id: ifttt
  alias: ifttt
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
    service_template: '{{ trigger.event.data.service }}'
- id: '1606097165594'
  alias: Master Bathroom Exhaust On
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.master_shower_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.master_bathroom_lights
    state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.master_bathroom_exhaust
  mode: single
- id: '1606097277736'
  alias: Master Bathroom Exhaust Off
  description: ''
  trigger:
  - platform: state
    entity_id: switch.master_bathroom_lights
    from: 'on'
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.master_bathroom_exhaust
      state: 'on'
  action:
  - delay: 00:05:00
  - service: switch.turn_off
    data: {}
    entity_id: switch.master_bathroom_exhaust
  mode: single
- id: '1606145599838'
  alias: Attic Light On
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.attic_pico
    to: '1'
    from: '0'
  - type: opened
    platform: device
    device_id: ccc7657de72b463484c79434a14cb462
    entity_id: binary_sensor.samjin_multi_d65d0001_ias_zone
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: light.attic
    state: 'off'
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.attic
  mode: single
- id: '1606145879915'
  alias: Attic Light Off
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.attic_pico
    from: '0'
    to: '4'
  - type: not_opened
    platform: device
    device_id: ccc7657de72b463484c79434a14cb462
    entity_id: binary_sensor.samjin_multi_d65d0001_ias_zone
    domain: binary_sensor
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.attic
      state: 'on'
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.attic
  mode: single
- id: '1606146897917'
  alias: Night HVAC
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
    from: above_horizon
    to: below_horizon
  condition:
  - condition: state
    entity_id: input_boolean.away
    state: 'off'
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: Night
    entity_id: climate.my_ecobee
  mode: single
- id: '1606187210254'
  alias: Dryer Done Push Notification
  description: ''
  trigger:
  - platform: state
    entity_id: switch.momentary_dryer
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
  - service: notify.mobile_app_michaels_iphone
    data:
      message: The Dryer is Done
  - service: notify.mobile_app_pixel_3a_xl
    data:
      message: The Dryer is Done
  - delay: 00:01:00
  mode: single
- id: '1606187325141'
  alias: Dryer Done Alexa Notification
  description: ''
  trigger:
  - platform: state
    entity_id: switch.momentary_dryer
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.away
    state: 'off'
  action:
  - service: notify.alexa_media_kitchen_echo_show
    data:
      message: The Dryer is Done
      data:
        type: tts
  - delay: 00:01:00
  mode: single
- id: '1606254459560'
  alias: Washer Done Push Notification
  description: ''
  trigger:
  - platform: state
    entity_id: switch.momentary_washer
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
  - service: notify.mobile_app_pixel_3a_xl
    data:
      message: The Washing Machine is Done
  - service: notify.mobile_app_michaels_iphone
    data:
      message: The Washing Machine is Done
  mode: single
- id: '1606254687081'
  alias: Washer Done Alexa Notification
  description: ''
  trigger:
  - platform: state
    entity_id: switch.momentary_washer
  condition:
  - condition: state
    entity_id: input_boolean.away
    state: 'off'
  action:
  - service: notify.alexa_media_kitchen_echo_show
    data:
      message: The Washing Machine is Done
      data:
        type: tts
  - delay: 00:01:00
  mode: single
- id: '1606254864498'
  alias: Water Valve Push Notification
  description: ''
  trigger:
  - platform: state
    entity_id: switch.water_valve
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: notify.mobile_app_michaels_iphone
    data:
      message: Water Leak Detected, Valve Closed
  - service: notify.mobile_app_pixel_3a_xl
    data:
      message: Water Leak Detected, Valve Closed
  mode: single
- id: '1606254934964'
  alias: Water Valve Alexa Notification
  description: ''
  trigger:
  - platform: state
    entity_id: switch.water_valve
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.away
    state: 'off'
  action:
  - service: notify.alexa_media_kitchen_echo_show
    data:
      message: Water has been Detected and the Valve has been Closed
  - delay: 00:01:00
  mode: single
- id: '1606447761355'
  alias: Night
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 75
    entity_id: light.exterior_back_yard_lights
  - service: switch.turn_on
    data: {}
    entity_id: switch.exterior_back_deck_lights
  - service: light.turn_on
    data:
      brightness_pct: 75
    entity_id: light.exterior_front_porch_lights
  - service: switch.turn_on
    data: {}
    entity_id: switch.exterior_side_door_light
  - service: light.turn_on
    data:
      brightness_pct: 25
    entity_id: light.front_foyer_pendants
  - service: light.turn_on
    data:
      brightness_pct: 25
    entity_id: light.living_room_floor_lamp
  - service: light.turn_on
    data:
      brightness_pct: 50
    entity_id: light.kitchen_sink_light
  - service: light.turn_on
    data:
      entity_id: light.hallway_night_light
      rgb_color:
      - 255
      - 160
      - 39
      brightness: 2
    entity_id: light.hallway_night_light
  mode: single
- id: '1606752037490'
  alias: Living Room TV On
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.living_room_tv_power_on
    from: 'off'
    to: 'on'
  condition:
  - condition: device
    device_id: 7207a6e5a3f54eca855e21119d5a778f
    domain: media_player
    entity_id: media_player.living_room_samsung_tv
    type: is_off
  action:
  - service: media_player.turn_on
    data:
      entity_id: media_player.living_room_samsung_tv
  mode: single
- id: '1606752125196'
  alias: Living Room TV Off
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.living_room_tv_power_off
    from: 'off'
    to: 'on'
  condition:
  - condition: device
    device_id: 7207a6e5a3f54eca855e21119d5a778f
    domain: media_player
    entity_id: media_player.living_room_samsung_tv
    type: is_on
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.living_room_samsung_tv
  mode: single
- id: '1607530527560'
  alias: Mike Away
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.life360_mike_salerno
    from: home
    to: not_home
  condition:
  - condition: state
    entity_id: device_tracker.life360_stephanie
    state: not_home
  - condition: state
    entity_id: input_boolean.guests
    state: 'off'
  action:
  - service: media_player.turn_off
    data: {}
    entity_id: media_player.living_room_samsung_tv
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    entity_id: climate.my_ecobee
  - service: alarm_control_panel.alarm_arm_away
    data: {}
    entity_id: alarm_control_panel.ring_alarm
  - service: lock.lock
    data: {}
    entity_id: lock.front_door, lock.inside_garage_door, lock.side_door
  - service: light.turn_off
    data: {}
    entity_id: light.dining_room_chandelier, light.antonella_s_bedroom_lights, light.office_lights,
      light.living_room_lights, light.kitchen_sink_light, light.master_bedroom_lights,
      light.kitchen_lights, light.garage_lights, light.family_room_lights, light.upstairs_hallway_lights,
      light.master_bedroom_mike_s_lamp, light.master_bedroom_stephanie_s_lamp, light.family_room_accent_lights,
      light.downstairs_hallway_lights, light.main_bathroom_lights, light.living_room_floor_lamp
  - service: switch.turn_off
    data: {}
    entity_id: switch.master_bathroom_lights, switch.master_bedroom_closet_light,
      switch.dominic_s_bedroom_closet_light, switch.utility_room_lights, switch.antonella_s_closet_lights
  - service: switch.turn_off
    data: {}
    entity_id: switch.left_garage_door, switch.right_garage_door
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.away
  mode: single
- id: '1607530782037'
  alias: Stephanie Away
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.life360_stephanie
    from: home
    to: not_home
  condition:
  - condition: state
    entity_id: device_tracker.life360_mike_salerno
    state: not_home
  - condition: state
    entity_id: input_boolean.guests
    state: 'off'
  action:
  - service: media_player.turn_off
    data: {}
    entity_id: media_player.living_room_samsung_tv
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    entity_id: climate.my_ecobee
  - service: alarm_control_panel.alarm_arm_away
    data: {}
    entity_id: alarm_control_panel.ring_alarm
  - service: lock.lock
    data: {}
    entity_id: lock.front_door, lock.inside_garage_door, lock.side_door
  - service: light.turn_off
    data: {}
    entity_id: light.dining_room_chandelier, light.antonella_s_bedroom_lights, light.office_lights,
      light.living_room_lights, light.kitchen_sink_light, light.master_bedroom_lights,
      light.kitchen_lights, light.garage_lights, light.family_room_lights, light.upstairs_hallway_lights,
      light.master_bedroom_mike_s_lamp, light.master_bedroom_stephanie_s_lamp, light.family_room_accent_lights,
      light.downstairs_hallway_lights, light.main_bathroom_lights, light.living_room_floor_lamp
  - service: switch.turn_off
    data: {}
    entity_id: switch.master_bathroom_lights, switch.master_bedroom_closet_light,
      switch.dominic_s_bedroom_closet_light, switch.utility_room_lights, switch.antonella_s_closet_lights
  - service: switch.turn_off
    data: {}
    entity_id: switch.left_garage_door, switch.right_garage_door
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.away
  mode: single
- id: '1607531102243'
  alias: Home Day
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.life360_mike_salerno
    from: not_home
    to: home
  - platform: state
    entity_id: device_tracker.life360_stephanie
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: home
    entity_id: climate.my_ecobee
  - service: lock.unlock
    data: {}
    entity_id: lock.inside_garage_door
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.away
  - service: switch.turn_on
    data: {}
    entity_id: switch.left_garage_door, switch.right_garage_door
  mode: single
- id: '1607531362964'
  alias: Home Night
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.life360_mike_salerno
    from: not_home
    to: home
  - platform: state
    entity_id: device_tracker.life360_stephanie
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: Night
    entity_id: climate.my_ecobee
  - service: lock.unlock
    data: {}
    entity_id: lock.inside_garage_door
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.away
  - service: switch.turn_on
    data: {}
    entity_id: switch.left_garage_door, switch.right_garage_door
  mode: single
